use_frameworks!

target 'Mocky_Example' do
    pod 'RxSwift'
    pod 'Mocky/AutoMockable', :path => '../'
  target 'Mocky_Tests' do
    inherit! :search_paths
  	pod 'Mocky', :path => '../'
    pod 'RxBlocking'
  end
end
