task :mock do
	sh "cp -r ../Mocky/Templates ./Mocky-Templates"
	sh "Pods/Sourcery/bin/sourcery --config mocky.yml --disableCache"
	sh "rm -r -f ./Mocky-Templates"
end

task :debug do
	sh "cp -r ../Mocky/Templates ./Mocky-Templates"
	sh "Pods/Sourcery/bin/sourcery --config mocky.yml --disableCache --verbose"
	sh "rm -r -f ./Mocky-Templates"
end

desc "Install project dependencies"
desc "In case of need, pod repo update will be invoked"
task :pod_install do
	begin
		sh "pod install"
	rescue
		sh "pod repo update"
		sh "pod install"
	end
end
