author: Przemysław Wośko, Andrzej Michnia
author_url: https://girappe.com
module: SwiftyMocky
sourcekitten_sourcefile: docs.json
module_version: 4.2.0
github_url: https://github.com/MakeAWishFoundation/SwiftyMocky
copyright: 'Copyright © 2017 MakeAWishFoundation. All rights reserved.'
readme: guides/Overview.md
documentation: guides/*.md

custom_categories:
  - name: Main Guides
    children:
      - Overview
      - Installation
      - Setup in project
      - Mockfile
      - Command Line Interface
      - Supported features
      - Prototyping

  - name: Additional Guides
    children:
      - Matcher support for not Equatable
      - Handling Generics
      - Examples
      - Legacy
      - Add XCode generate action
      - Known issues
      - CHANGELOG

  - name: Global methods
    children:
      - Given(_:_:_:)
      - Perform(_:_:)
      - Verify(_:_:file:line:)
      - Verify(_:_:_:file:line:)

  - name: Configuration
    children:
      - StubbingPolicy
      - SequencingPolicy

  - name: Types
    children:
      - Mock
      - StaticMock
      - Parameter
      - Matcher
      - Countable
      - Count
      - Stubber
      - StubberThrows

  - name: Generics
    children:
      - GenericAttribute
      - GenericAttributeType

  - name: Helpers
    children:
      - XCTAssertThrowsError(_:of:_:file:line:)
      - XCTAssertThrowsError(_:error:_:file:line:)
      - MockyAssertion

  - name: Internal
    children:
      - SwiftyMockyTestObserver
      - FatalErrorUtil
      - OptionalType
      - WithSequencingPolicy
      - WithStaticSequencingPolicy
      - WithStubbingPolicy
      - Int
      - Optional
      - UInt
      - MockError
      - StubProduct
      - StubbedMethod
      - Failure(_:)
      - MockyAssert(_:_:file:line:)
