fastlane_version "2.51.0"

default_platform :ios

platform :ios do
    desc "Runs all the tests"
    lane :test do
        scan(
            scheme: "Mocky_Tests_iOS",
            workspace: "./SwiftyMocky.xcworkspace",
            devices: ["iPhone 11"]
        )
    end
end
